server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://127.0.0.1:7002/eureka
spring:
  application:
    name: cloud-order-consumer